# Generated by Django 4.2.7 on 2024-03-07 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reels",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tag", models.CharField(max_length=32)),
                ("reel_video", models.FileField(upload_to="media/reels/")),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("is_let_template", models.BooleanField(default=False)),
                ("is_hide_count_likes", models.BooleanField(default=False)),
                ("is_show_captions", models.BooleanField(default=True)),
                ("is_high_quality", models.BooleanField(default=False)),
                ("caption", models.TextField()),
                ("number_of_likes", models.PositiveIntegerField(default=0)),
                ("number_of_comments", models.PositiveIntegerField(default=0)),
                ("number_of_sends", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="reels", to="post.profile"
                    ),
                ),
            ],
            options={
                "verbose_name": "Reels",
                "verbose_name_plural": "Reels",
            },
        ),
        migrations.AlterField(
            model_name="commentreel",
            name="reel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="commented_reel", to="post.reels"
            ),
        ),
        migrations.AlterField(
            model_name="likesreel",
            name="reel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="reel_likes", to="post.reels"
            ),
        ),
        migrations.DeleteModel(
            name="Reel",
        ),
    ]
